[package]
name = "vmulti-client"
version = "0.1.0"
authors = ["vagola <vladislavs.golubs@yandex.ru>"]
edition = "2018"

[dependencies]
libc = "0.2"
winapi = { version = "0.3", features = ["hidsdi", "cfgmgr32", "fileapi", "handleapi", "hidpi", "errhandlingapi"] }
